Blog/urls.py
from django.urls import path, include
from . import views
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import ArticleSitemap
from .feeds import LatestArticlesFeed
from blog.forms import ArticleForm

app_name = 'blog'

sitemaps = {
    'articles': ArticleSitemap,
}

urlpatterns = [
    path('', views.article_list, name = 'article_list'),
    path('<slug>', views.article_list, name = 'article_list_by_category'),
    path('article/add', views.add_article, name='add_article'),
    path('article/like', views.like_article, name='like_article'),
    path('comment/like', views.like_comment, name='like_comment'),
    path('category/add', views.add_category, name='add_category'),
    path('articles/<int:id>', views.article_detail, name='article_detail'),
    path('article/edit/<int:pk>', views.ArticleUpdateView.as_view(), name='article_edit'),
    path('article/delete/<int:pk>', views.ArticleDeleteView.as_view(), name='article_delete'),
    path('article/share/<int:pk>', views.article_share, name='article_share'),
    path('schemas/sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('article/feed', LatestArticlesFeed(), name='article_feed'),
    path('article/search', views.article_search, name='article_search'),
    path('ajax/mark_notification_as_read', views.mark_notification_as_read, name='mark_notification_as_read'),
    path('ajax/mark_all_notifications_as_read', views.mark_all_notifications_as_read, name='mark_all_notifications_as_read'),
    path('elasticsearch_results/', views.ElasticSearchView.as_view(), name='elasticsearch_results'),
    path('ajax/add_bookmark', views.add_bookmark, name='add_bookmark')
]

templates/notifications/friend_request_notice.html
<script type="text/javascript">
$(document).ready(function(){
  $('#notification_active').on('click', function(){
    let id = $(this).attr('data-id')
    let user_id = $(this).attr('data-user-id')
    $.ajax({
      type: 'POST',
      url: '{% url "blog:mark_notification_as_read" %}',
      data: {'id': id, 'csrfmiddlewaretoken': '{{csrf_token}}'},
      dataType: 'json',
      success: function(response){
        if (response.marked)
          window.location.href = "https://myblog.com/accounts/"+user_id;
        else
          console.log('Notification not found.')
      },
      error: function(rs, e){
        console.log(rs.responseText);
      }
    });
  })
})
</script>
<div class="alert alert-block alert-{{ notice.level }}">
  <a class="close" href="{% url 'notifications:mark_as_read' notice.slug %}">
    <i class="fa fa-times"></i>
  </a>
  <h4>
    <i class="icon-mail{% if notice.unread %}-alt{% endif %}"></i>
    {{ notice.actor.get_full_name }}
    {{ notice.verb }}
    {% if notice.target %}
      of {{ notice.target }}
    {% endif %}
  </h4>
  <p>{{ notice.timesince }} ago</p>

  <a id='notification_active' href='javascript:void(0);' data-id={{notice.id}} data-user-id="{{notice.action_object.id}}">{{notice.action_object.get_full_name}}</a><br>

  <div class="notice-actions">
    {% for action in notice.data.actions %}
      <a class="btn" href="{{ action.href }}">{{ action.title }}</a>
    {% endfor %}
  </div>

</div>

templates/notifications/list.html
{% extends 'blog/base.html'%}

{% block page %}
<br><br><br><br>
<script type="text/javascript">
$(document).ready(function(){
  console.log(window.location.pathname)
  if (window.location.pathname == '/inbox/notifications/unread/')
    $('#mark_all_notifications_as_read').style.display = 'block'

  else
    $('.close').remove()


  $('#mark_all_notifications_as_read').on('click', function(){
    $.ajax({
      type: 'POST',
      url: '{% url "blog:mark_all_notifications_as_read" %}',
      data: {'session_key': '{{request.session.session_key|escapejs}}', 'csrfmiddlewaretoken': '{{csrf_token|escapejs}}'},
      dataType: 'json',
      success: function(response)
      {
        console.log(response)
        location.reload()
      },
      error: function(rs, e){
        console.log(rs.responseText);
      }
    });
  })
})
</script>
<ul class="notifications">
  {% if notifications %}
    <button style='display: None' type="button" class="btn btn-danger" id="mark_all_notifications_as_read"></button>
  {% else %}
    <p>No notifications yet.</p>
  {% endif %}

  {% for notice in notifications %}
    {% if notice.description == 'friend_request' %}
      {% include 'notifications/friend_request_notice.html' %}
    {% else %}
      {% include 'notifications/notice.html' %}
    {% endif %}
  {% endfor %}
</ul>
{% endblock %}

templates/notifications/notice.html
<script type="text/javascript">
$(document).ready(function(){
  $('#notification_active').on('click', function(){
    let id = $(this).attr('data-id')
    let article_id = $(this).attr('data-article-id')
    $.ajax({
      type: 'POST',
      url: '{% url "blog:mark_notification_as_read" %}',
      data: {'id': id, 'csrfmiddlewaretoken': '{{csrf_token}}'},
      dataType: 'json',
      success: function(response){
        if (response.marked)
          window.location.href = "https://myblog.com/ws/article/"+article_id;
        else
          console.log('Notification not found.')
      },
      error: function(rs, e){
        console.log(rs.responseText);
      }
    });
  })
})

</script>
<div class="alert alert-block alert-{{ notice.level }}">
  <a class="close" href="{% url 'notifications:mark_as_read' notice.slug %}">
    <i class="fa fa-times"></i>
  </a>
  <h4>
    <i class="icon-mail{% if notice.unread %}-alt{% endif %}"></i>
    {{ notice.actor }}
    {{ notice.verb }}
    {% if notice.target %}
      of {{ notice.target }}
    {% endif %}
  </h4>

  <p>{{ notice.timesince }} ago</p>

  <a id='notification_active' href='javascript:void(0);' data-id={{notice.id}} data-article-id="{{notice.action_object.id}}">{{notice.action_object.title}}</a><br>
  <p>{{notice.action_object.description}}</p>

  <div class="notice-actions">
    {% for action in notice.data.actions %}
      <a class="btn" href="{{ action.href }}">{{ action.title }}</a>
    {% endfor %}
  </div>

</div>

templates/notifications/test_tags.html
{% load notifications_tags %}

{% register_notify_callbacks callbacks='fill_notification_menu,fill_notification_badge' %}

{% notifications_unread as unread %}
{{ unread }}
{% live_notify_badge %}
{% live_notify_list %}