Blog/api/urls.py
from . import views
from rest_framework import routers

router = routers.DefaultRouter()
router.register('categories', views.CategoryViewSet)
router.register('articles', views.ArticleViewSet)
router.register('comments', views.CommentViewSet)

Blog/urls.py
from django.urls import path, include
from . import views
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import ArticleSitemap
from .feeds import LatestArticlesFeed
from blog.forms import ArticleForm

app_name = 'blog'

sitemaps = {
    'articles': ArticleSitemap,
}

urlpatterns = [
    path('', views.article_list, name = 'article_list'),
    path('<slug>', views.article_list, name = 'article_list_by_category'),
    path('article/add', views.add_article, name='add_article'),
    path('article/like', views.like_article, name='like_article'),
    path('comment/like', views.like_comment, name='like_comment'),
    path('category/add', views.add_category, name='add_category'),
    path('articles/<int:id>', views.article_detail, name='article_detail'),
    path('article/edit/<int:pk>', views.ArticleUpdateView.as_view(), name='article_edit'),
    path('article/delete/<int:pk>', views.ArticleDeleteView.as_view(), name='article_delete'),
    path('article/share/<int:pk>', views.article_share, name='article_share'),
    path('schemas/sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('article/feed', LatestArticlesFeed(), name='article_feed'),
    path('article/search', views.article_search, name='article_search'),
    path('ajax/mark_notification_as_read', views.mark_notification_as_read, name='mark_notification_as_read'),
    path('ajax/mark_all_notifications_as_read', views.mark_all_notifications_as_read, name='mark_all_notifications_as_read'),
    path('elasticsearch_results/', views.ElasticSearchView.as_view(), name='elasticsearch_results'),
    path('ajax/add_bookmark', views.add_bookmark, name='add_bookmark')
]

Blog/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
from django.urls import reverse
from taggit.managers import TaggableManager

class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='Category', db_index=True, unique=True)
    slug = models.SlugField(max_length=100, db_index=True, unique=True)
    not_sended = models.BooleanField(default = False)

    class Meta:
        ordering=['name']

    def get_absolute_url(self):
        return reverse('blog:article_list_by_category', args=[str(self.slug)])

    def __str__(self):
        return self.name

class MathManager(models.Manager):
    def get_queryset(self):
        return super(MathManager, self).get_queryset().filter(category = 2)

class Article(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='article', blank=False)
    category = models.ManyToManyField(Category)
    tags = TaggableManager()
    title = models.CharField(max_length=100, verbose_name='Title')
    image = models.ImageField('image', upload_to='blog/articles/images', blank=True)
    description = models.CharField(max_length=450, verbose_name='Description')
    text = models.TextField(verbose_name='Text')
    like = models.ManyToManyField(User, related_name='likes', blank = True)
    post_date = models.DateTimeField(auto_now=True, verbose_name='Post Date')

    objects = models.Manager()
    math = MathManager()

    class Meta:
        ordering = ('-post_date', )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:article_detail', args=[str(self.id)])

    def total_likes(self):
        return self.like.count()

    def get_image_url(self):
        if not self.image:
            return '/static/default_images/article_default_image.jpg'
        return self.image.url

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name="comments")
    text = models.TextField(max_length=1000)
    user = models.ForeignKey(User,on_delete=models.CASCADE,)
    post_date=models.DateTimeField(default=datetime.now, verbose_name='Post Date')
    comment_likes=models.ManyToManyField(User, related_name='comment_likes', blank = True)

    def __str__(self):
        return self.text[:20]

    def total_likes(self):
        return self.comment_likes.count()

class Bookmark(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name="bookmarks")
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='bookmarked_articles')
    date = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ('article', 'user')

Blog/forms.py
from django.contrib.auth.models import User
from django import forms
from blog.models import Article, Category, Comment
from datetime import datetime
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget
from django.contrib.auth.password_validation import validate_password

class CategoryForm(forms.ModelForm):
    class Meta:
        model=Category
        fields=('name', )

class ArticleForm(forms.ModelForm):
    title = forms.CharField(required=True)
    description = forms.CharField(required=True)
    category = forms.ModelMultipleChoiceField(queryset=Category.objects.all(), widget=forms.SelectMultiple, required=True)
    text = forms.CharField(widget=SummernoteWidget(), required=True)

    field_order = ['title', 'description', 'category','tags', 'text']
    class Meta:
        model = Article
        fields = {'title', 'description', 'category', 'tags', 'text'}

class ArticleUpdateForm(forms.ModelForm):
    text = forms.CharField(widget=SummernoteWidget())
    class Meta:
        model=Article
        fields=('title','description', 'text', 'category', 'tags')

class CommentForm(forms.ModelForm):
    field_order = ['text']
    class Meta:
        model=Comment
        fields=('text',)


class EmailArticleForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget = forms.Textarea)

class SearchForm(forms.Form):
    query = forms.CharField()

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile, Preference
from datetime import datetime
from django.contrib.auth.password_validation import validate_password
from allauth.account.forms import SignupForm
from allauth.account.forms import SignupForm
from allauth.account.adapter import get_adapter


class CustomSignupForm(SignupForm):
    first_name = forms.CharField(max_length=30, label='First Name')
    last_name = forms.CharField(max_length=30, label='Last Name')

    def clean_username(self):
        super().clean_username()
        
        value = self.cleaned_data['username']
        try:
            value.encode(encoding='utf-8').decode('ascii')
        except:
            raise forms.ValidationError("Login can only contains english letters.")
        return value

class UserForm(forms.ModelForm):
    username = forms.CharField(max_length = 100, required = True)
    password = forms.CharField(widget = forms.PasswordInput())
    confirm_password = forms.CharField(widget=forms.PasswordInput())
    date_joined = forms.DateTimeField(widget = forms.HiddenInput, initial = datetime.now)
    field_order = ['first_name', 'last_name', 'username', 'email', 'password', 'confirm_password', 'date_joined']

    class Meta:
        model = User
        fields = {'first_name', 'last_name', 'username', 'email', 'password', 'confirm_password', 'date_joined'}

    def is_english(self, s):
        try:
            s.encode(encoding='utf-8').decode('ascii')
        except UnicodeDecodeError:
            return False
        else:
            return True

    def clean(self):
        super(UserForm, self).clean()
        first_name = self.cleaned_data.get('first_name')
        last_name = self.cleaned_data.get('last_name')
        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get("confirm_password")

        if password != confirm_password:
            raise forms.ValidationError("Passwords does not match")

        if not first_name.isalpha():
            self._errors['first_name'] = self.error_class(['Please enter correct first name. Use only alphabetical characters (a-z, A–Z)'])

        if not last_name.isalpha():
            self._errors['last_name'] = self.error_class(['Please enter correct last name. Use only alphabetical characters (a-z, A–Z)'])

        try:
            validate_password(password)
        except forms.ValidationError as e:
            self._errors['password'] = self.error_class(e)

        del self.cleaned_data['confirm_password']
        return self.cleaned_data

class PreferenceForm(forms.ModelForm):
    class Meta:
        model = Preference
        fields = {'name'}

class ProfileCreateUpdateForm(forms.ModelForm):
    preferences = forms.ModelMultipleChoiceField(queryset=Preference.objects.all(), widget=forms.SelectMultiple)

    class Meta:
        model = Profile
        fields = ('preferences', 'image', 'is_subscribed_to_the_newsletter')


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields=('first_name', 'last_name')

Blog/api/views.py
from blog.models import Category, Article, Comment
from .serializers import CategorySerializer, ArticleSerializer, CommentSerializer
from rest_framework import viewsets
from rest_framework import permissions
from rest_framework.permissions import IsAuthenticated, AllowAny
from Blog.permissions import IsOwnerOrReadOnly, IsAdminUserOrReadOnly


class CategoryViewSet(viewsets.ModelViewSet):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer
    permission_classes = [IsAdminUserOrReadOnly]

class ArticleViewSet(viewsets.ModelViewSet):
    queryset = Article.objects.select_related('user').prefetch_related('tags', 'category', 'like', 'comments', 'comments__user', 'comments__comment_likes').all()\
    .defer('user__password', 'user__username', 'user__email', 'user__last_login', 'user__is_superuser', 'user__is_staff', 'user__is_active', 'user__date_joined')

    serializer_class = ArticleSerializer
    permission_classes = [AllowAny]

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)

class CommentViewSet(viewsets.ModelViewSet):
    queryset = Comment.objects.select_related('user').prefetch_related('comment_likes').all()\
    .defer('user__password', 'user__username', 'user__email', 'user__last_login', 'user__is_superuser', 'user__is_staff', 'user__is_active', 'user__date_joined')

    serializer_class = CommentSerializer
    permission_classes = [IsAuthenticated, IsOwnerOrReadOnly]

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)

templates/blog/add_article(old).html
{% extends 'blog/base.html'%}
{% block title %}Add article{% endblock %}

{% block page %}
  <br><br><br><br>
  <a href="{% url 'blog:add_category'%}">+Add Category</a>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{article_form.as_p}}
    <button type="submit">Add</button>
  </form>
{% endblock %}

templates/blog/article_detail.html
{% extends 'blog/base.html' %}
{% load static %}
{% block title %}{{article.title}}{% endblock %}

{% block css %}
  <link type="text/css" rel="stylesheet" href="{% static 'blog/css/article.css' %}">
{% endblock %}


{% block page %}
<div class="all">
  <div class="similar" style="margin-left: 30px;margin-top: 55px;">
    {% for similar_article in similar_articles %}
      <div class="news">
          <img src="{{similar_article.get_image_url}}" >
          <p style='position: relative;
          display: -webkit-box;
          -webkit-line-clamp: 3;
          -webkit-box-orient: vertical;
          overflow: hidden;'>
            <a href="#">{{similar_article.title}}</a><br>
            {{similar_article.description}}
          </p>
          <div class="posttime">
            <small>
              <div class="time">
                <i class="fa fa-clock"></i>{{similar_article.post_date}}
              </div>
            </small>
          </div>
      </div>
    {% endfor %}
  </div>
  <div class="top">
      <div class="col-md-10 col-sm-12 col-11 article">
          <h3>{{article.title}}</h3>
          <small>
            <div class="time">
              <i class="fa fa-clock"></i>{{article.post_date}}
             </div>
             <div id="category">
                {% for category in article.category.all%}
                    {{category}}
                  {% if not forloop.last %} |
                  {% endif %}
                {% endfor %}
            </div>
          </small>
          <img style="width: 100%;max-width: 100%;height: 450px;margin-bottom: 50px;" src="{{article.get_image_url}}" alt="">
          <p>{{article.text|safe }}</p>
          <div class="box">
              <div class="box_item box_item_border_right">
                  <button type="submit" id="id_article" name="article_id" value="{{article.pk}}" class='button_like_a {% if is_article_liked %}active{%else%}inactive{%endif%}' ><i class="far fa-thumbs-up"></i></button>
              </div>
              <div class="box_item box_item_border_right">
                  <button type="submit" class='button_like_a {% if is_bookmarked %}active{%else%}inactive{%endif%}' id="id_bookmark" value="{{article.pk}}"><i class="far fa-bookmark"></i></buttom>
              </div>
              {% if request.user == article.user%}
                <div class="box_item box_item_border_right active">
                    <a href="{% url 'blog:article_edit' article.pk %}"><i class="fas fa-edit"></i></a>
                </div>
                <div class="box_item active">
                    <a href="{% url 'blog:article_delete' article.pk %}"><i class="fas fa-trash"></i></a>
                </div>
              {% else %}
                <div class="box_item box_item_border_right">
                    <button class="button_like_a disabled_button" disabled><i class="fas fa-edit"></i></button>
                </div>
                <div class="box_item">
                    <button class="button_like_a disabled_button" disabled><i class="fas fa-trash"></i></button>
                </div>
              {% endif %}

          </div>
          <h4>Comments : <span id="comments_count">{{comments_count}}</span></h4>
            {% if request.user.is_authenticated %}

              <form method="post" id='comment'>
                <div class="form-group">
                {% csrf_token %}
                <textarea name="{{comment_form.text.html_name}}" id="{{comment_form.text.id_for_label}}" maxlength="{{comment_form.text.field.max_length}}" class="form-control" rows="3" required></textarea>
                </div>
                <button class="btn btn-primary">Post</button>
              </form>

            {% else %}
              <p><a href="{% url 'account_login' %}?next={% url 'blog:article_detail' article.id %}">Please login</a></p>
            {% endif %}
          <div class="comments">
            {% for comment in comments %}
              <div class="media g-mb-30 media-comment">
                  <img class="d-flex g-width-50 g-height-50 rounded-circle g-mt-3 g-mr-15" src="{{comment.user.profile.get_image_url}}" alt="No">
                  <div class="media-body u-shadow-v18 g-bg-secondary g-pa-30">
                      <div class="g-mb-15">
                          <h5 class="h5 g-color-gray-dark-v1 mb-0"><a href="{%url 'profile' comment.user.id%}" style="color:inherit">{{comment.user.get_full_name}}</a></h5>
                          <span class="g-color-gray-dark-v4 g-font-size-12">{{comment.post_date}}</span>
                      </div>
                      <p>{{comment.text}}</p>


                  <div id="comment_like_section_{{comment.id}}">
                    {% if request.user.is_authenticated %}
                        <form action="{% url 'blog:like_comment' %}" method="post">
                        {% csrf_token %}
                          <button type="submit" id = "comment_like" name="comment_id" value = "{{comment.pk}}" class="comment_like {% if request.user in comment.comment_likes.all %}liked{% else %}unliked{% endif %}" class="comment_like">
                            <i class="fa fa-thumbs-up g-pos-rel g-top-1 g-mr-3"></i> <span id="comment_likes_count">{{comment.likes_count}}</span>
                          </button>
                        </form>
                    {% endif %}
                  </div>


                  </div>
              </div>
            {% endfor %}
          </div>
      </div>
  </div>
</div>

<script>
    $(document).ready(function(){
      if (document.location.protocol === 'https:')
        websocket_protocol = 'wss://';
      else
        websocket_protocol = 'ws://';

      var socket_url = websocket_protocol + window.location.host + '/ws' + window.location.pathname;
      var socket = new WebSocket(socket_url);

      socket.onmessage = function(event){
          let new_comment = JSON.parse(event.data)
          $('.comments').prepend('<div class="media g-mb-30 media-comment"><img class="d-flex g-width-50 g-height-50 rounded-circle g-mt-3 g-mr-15" src="' + new_comment.user_image_url + '" alt="Image Description"><div class="media-body u-shadow-v18 g-bg-secondary g-pa-30">'
          + '<div class="g-mb-15">' + '<h5 class="h5 g-color-gray-dark-v1 mb-0">' + new_comment.user + '</h5>'
          + '<span class="g-color-gray-dark-v4 g-font-size-12">'+ new_comment.post_date  + '</span></div>' + '<p>' + new_comment.comment_text + '</p>'+ '<div id="comment_like_section_'+ new_comment.id +'"><button type="submit" id="comment_like" name="comment_id" value="'+ new_comment.id +'" class="comment_like unliked"><i class="fa fa-thumbs-up g-pos-rel g-top-1 g-mr-3"></i><span id="comment_likes_count">0<span></button>' +'</div></div></div>')

          $('#comments_count').text(parseInt($('#comments_count').text()) + 1)

      };

      socket.onopen = function(event)
      {
          var form = $("#comment")
          form.submit(function(e){
              e.preventDefault()
              var comment_text = $('#id_text').val()
              data = {
                  'comment_text': comment_text,
              }
              socket.send(JSON.stringify(data))
              $('#id_text').val('')
          });

          $('#id_text').keypress(function(e){
              if (e.which == 13){
                  $("#comment").submit();
              }
          });
      };

      socket.onclose= function(event){
          console.log('Socket closed', event)
      };

      $(document).on('click', '.comment_like', function(event){
          event.preventDefault();
          var pk = $(this).attr('value');
          $.ajax({
            type: 'POST',
            url: '{% url "blog:like_comment" %}',
            data: {'id': pk, 'csrfmiddlewaretoken': '{{csrf_token}}'},
            dataType: 'json',
            success: function(response){
              if (response.status)
              {
                if (response.status == 'liked')
                {
                  diff = 1;
                  $('#comment_like_section_' + pk + ' #comment_like').removeClass('unliked');
                  $('#comment_like_section_' + pk + ' #comment_like').addClass('liked');

                }

                else if (response.status == 'unliked')
                {
                  diff = -1
                  $('#comment_like_section_' + pk + ' #comment_like').removeClass('liked');
                  $('#comment_like_section_' + pk + ' #comment_like').addClass('unliked');
                }

                $('#comment_like_section_' + pk + ' #comment_likes_count').text(parseInt($('#comment_like_section_' + pk + ' #comment_likes_count').text()) + diff)
              }
              else
                alert('We know you like what you write.')
            },
          });
      });

      $(document).on('click', '#id_article', function(event){
          event.preventDefault();
          var pk = $(this).attr('value');

          $.ajax({
            type: 'POST',
            url: '{% url "blog:like_article" %}',
            data: {'id': pk, 'csrfmiddlewaretoken': '{{csrf_token}}'},
            dataType: 'json',
            success: function(response){
              if (response.status)
              {
                console.log(response)
                if (response.status == 'liked')
                {
                  diff = 1;
                  $('#id_article').removeClass('inactive');
                  $('#id_article').addClass('active');

                }

                else if (response.status == 'unliked')
                {
                  diff = -1
                  $('#id_article').removeClass('active');
                  $('#id_article').addClass('inactive');
                }
                // $('#article_like_section_' + pk + ' #comment_likes_count').text(parseInt($('#comment_like_section_' + pk + ' #comment_likes_count').text()) + diff)
              }
              else
              {
                alert('We know you like what you write.')
              }
            },
            error: function(rs, e){
              console.log(rs.responseText);
            }
          });
      });

      $(document).on('click', '#id_bookmark', function(event){
          event.preventDefault();
          var pk = $(this).attr('value');

          $.ajax({
            type: 'POST',
            url: '{% url "blog:add_bookmark" %}',
            data: {'id': pk, 'csrfmiddlewaretoken': '{{csrf_token}}'},
            dataType: 'json',
            success: function(response){
              if (response.status == 'added')
                {
                  diff = 1;
                  $('#id_bookmark').removeClass('inactive');
                  $('#id_bookmark').addClass('active');

                }

                else if (response.status == 'removed')
                {
                  diff = -1
                  $('#id_bookmark').removeClass('active');
                  $('#id_bookmark').addClass('inactive');
                }
            },
            error: function(rs, e){
              console.log(rs.responseText);
            }
          });
      });
    })
</script>

{% endblock %}

templates/blog/article_like_section.html
{% if request.user.is_authenticated %}
  <form action="{% url 'blog:like_article'%}" method="post">
    {% csrf_token %}
    {% if is_article_liked %}
      <button type="submit" id = "article_like" name="article_id" value = "{{article.pk}}" class = 'btn btn-danger'>Dislike - <span>{{total_likes}}</span></button>
    {% else %}
      <button type="submit" id = "article_like" name="article_id" value = "{{article.pk}}" class = 'btn btn-primary'>Like - <span>{{total_likes}}</span></button>
    {% endif %}
  </form>
{% endif %}

templates/blog/comment_like_section(old).html
{% if request.user.is_authenticated %}
<form action="{% url 'blog:like_comment' %}" method="post">
  {% csrf_token %}
  {% if request.user in comment.comment_likes.all %}
    <button type="submit" id = "comment_like" name="comment_id" value = "{{comment.pk}}" class = 'btn btn-danger'>Dislike - <span>{{comment.total_likes}}</span></button>
  {% else %}
    <button type="submit" id = "comment_like" name="comment_id" value = "{{comment.pk}}" class = 'btn btn-primary'>Like - <span>{{comment.total_likes}}</span></button>
  {% endif %}
</form>
{% endif %}

templates/blog/get_article.html
{% extends 'blog/base.html' %}
{% load blog_tags %}
{% load static %}
{% block title %} Article {% endblock %}
{% block page %}
<script type="text/javascript">
  window.onscroll = function() {scrollFunction()};
  function scrollFunction() {
    if (document.body.scrollTop > 250 || document.documentElement.scrollTop > 250) {
      $(".icon-bar").show();
    } else {
      $(".icon-bar").hide();
    }
  }
</script>


<link rel="stylesheet" href="{% static 'blog/css/social-bar.css' %}">

<div class="icon-bar" style="display:none">
  <a href="https://www.facebook.com/sharer/sharer.php?u={{request.build_absolute_uri}}" class='facebook'><i class="fab fa-facebook-f"></i></a>
  <a href="https://twitter.com/home?status={{share_string_desc}}%20{{request.build_absolute_uri}}" class="twitter"><i class="fab fa-twitter"></i></a>
  <a href="https://plus.google.com/share?url={{request.build_absolute_uri}}" class="google"><i class="fab fa-google"></i></a>
  <a href="https://www.linkedin.com/shareArticle?mini=true&url={{request.build_absolute_uri}}&{{article.title}}&summary={{share_string_desc}}&source=={{request.build_absolute_uri}}" class="linkedin"><i class="fab fa-linkedin"></i></a>
  <a href="http://www.reddit.com/submit?url={{request.build_absolute_uri}}&title={{article.title}}" class="reddit"><i class="fab fa-reddit"></i></a>
  <a href='{% url "blog:article_share" article.pk  %}' class="email"><i class="fas fa-envelope"></i></a>
</div>
<!-- Page Header -->
  <header class="masthead" style="background-image: url( '{% static 'blog/img/post-bg.jpg' %}')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="post-heading">
            <h1>{{article.title}}</h1>
            <h2 class="subheading">{{article.description}}</h2>
            <span class="meta">Posted by
              <a href="#">{{article.user.get_full_name}}</a>
              on {{article.post_date}}</span>
          </div>
        </div>
      </div>
    </div>

  </header>

  <!-- Post Content -->
  <article>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <p>{{article.text | safe }}</p>

          <!-- <a href="#">
            <img class="img-fluid" src="{% static 'blog/img/post-sample-image.jpg' %} " alt="">
          </a>
          <span class="caption text-muted">To go places and do things that have never been done before – that’s what living is all about.</span> -->
        </div>
      </div>

      <hr>
      <div id="article_like_section">
        {% include 'blog/article_like_section.html' %}
      </div>
      <hr>

      {% if request.user == article.user %}
        <a class="btn btn-warning" href="{% url 'blog:article_edit' article.pk %}">Edit Blog Post</a>
        <a class="btn btn-danger" href="{% url 'blog:article_delete' article.pk %}"><i class="fa fa-trash"></i>Delete Blog Post</a>
      {% endif %}
      <hr>
      <hr>
      <div>
        {% get_most_commented_articles 5 %}
        </div>
      <div>
        <hr>
        {% get_most_liked_articles 5 %}
        <hr>
      </div>
      <div id = 'comments'>
      <h1>Comments</h1>

      {% for comment in article.comments.all %}
          <div class="comment">
              <strong>{{ comment.user.get_full_name }}</strong>
              <p>{{ comment.text |linebreaks }}</p>
              <div class="date">{{ comment.post_date }}</div>
          </div>

          <div id="comment_like_section_{{comment.id}}">
            {% include 'blog/comment_like_section.html' %}
          </div>
          <hr>
      {% empty %}
          <p>No comments here yet :(</p>
      {% endfor %}

      </div>
      {% if request.user.is_authenticated %}
        <form  method="post" id = 'comment' enctype="multipart/form-data">
          {% csrf_token %}
          {{comment_form.as_p}}
          <button type="submit">Add</button>
        </form>
      {% else %}
        <p><a href="{% url 'account_login' %}?next={% url 'blog:article_detail' article.id %}">Please login</a></p>
      {% endif %}
    </div>
  </article>

<script>
    $(document).ready(function(){
      if (document.location.protocol === 'https:')
        websocket_protocol = 'wss://';
      else
        websocket_protocol = 'ws://';

      var socket_url = websocket_protocol + window.location.host + '/ws' + window.location.pathname;
      var socket = new WebSocket(socket_url);

      socket.onmessage = function(event){
          console.log(event)
          var new_comment = JSON.parse(event.data)
          $('#comments').append('<div class="comment">' + '<strong>' + new_comment.user + '</strong>' + '<p>' + new_comment.comment_text
            + '</p>'+ '<div class="date">' + new_comment.post_date + '</div>' + '<div>' + new_comment.like + '</div>'
            + ' <div id = '+ 'comment_like_section_' + new_comment.id + ' > '
            + '<form action="/like_comment" method="post">' + '{% csrf_token %}'
            + '<button class = "btn btn-primary" type="submit" id = "comment_like" name="comment_id" value = ' + new_comment.id + '>'
            + 'Like - ' + '<span>' + 0 + '</span>' + '</button>' + '</div>'
            + '<hr>' + '</div>')

      };

      socket.onopen = function(event)
      {
          // comment
          console.log('Socket opened', event)
          var form = $("#comment")
          form.submit(function(e){
              e.preventDefault()
              var comment_text = $('#id_text').val()
              data = {
                  'comment_text': comment_text,
              }
              socket.send(JSON.stringify(data))
              $('#id_text').val('')
          });

          $('#id_text').keypress(function(e){
              if (e.which == 13){
                  $("#comment").submit();
              }
          });

      };

      socket.onclose= function(event){
          console.log('Socket closed', event)
      };


      $(document).on('click', '#comment_like', function(event){
          event.preventDefault();
          var pk = $(this).attr('value');
          $.ajax({
            type: 'POST',
            url: '{% url "blog:like_comment" %}',
            data: {'id': pk, 'csrfmiddlewaretoken': '{{csrf_token}}'},
            dataType: 'json',
            success: function(response){
              $('#comment_like_section_' + pk).html(response['form'])
            },
          });
      });

      $(document).on('click', '#article_like', function(event){
          event.preventDefault();
          var pk = $(this).attr('value');
          $.ajax({
            type: 'POST',
            url: '{% url "blog:like_article" %}',
            data: {'id': pk, 'csrfmiddlewaretoken': '{{csrf_token}}'},
            dataType: 'json',
            success: function(response){
              $('#article_like_section').html(response['form'])
            },
            error: function(rs, e){
              console.log(rs.responseText);
            }
          });
      });
    })
</script>
<br>

{% endblock page %}

templates/blog/latest_articles.html
<h3 class="post-subtitle">Latest articles</h3>
<ul>
  {% for article in latest_articles %}
    <li style='list-style-type: none;'>
      <a href="{{ article.get_absolute_url }}">{{ article.title }}</a>
    </li>
  {% endfor %}
</ul>

templates/blog/preferences.html
<h4>Preferences</h4>
<select name="preferences" id="id_preferences" multiple required>
    <span class="multiselect-selected-text">Choose your preferneces</span>
    {% for preference in preferences %}
      <option value="{{preference.id}}">{{preference.name}}</option>
    {% endfor %}
</select>

templates/blog/profile_articles.html
<div class="tab-pane fade" id="categories" role="tabpanel" aria-labelledby="categories-tab">
    <div class="container" id='id_articles'>
    </div>

    <div class="sh-pagination sh-default-color">
        <ul id="id_pagination" class="page-numbers">
        </ul>
    </div>
</div>